Rework to use on Linux
afedchin/screensaver.shadertoy pull request #12
Opened 2019-02-09 04:57 UTC by AlwinEsch

This adds code for processing OpenGL.

In addition, the settings are extended to include your own files from Shadertoy.

Furthermore fanart and screenshots are added, which the user sees what it brings.

In the shaders a lot had to be changed, so I'm not sure if they still work under Windows.

But noticed that in the addon no needed textures of the Shadertoy shaders are available and probably never really worked properly.

If someone has DirextX knowledges he might be able to attack it.

2019-02-09 07:00 UTC, afedchin commented
did you test this on windows? because shaders were adapted and changes may break them

2019-02-09 18:33 UTC, AlwinEsch commented
No, unfortunately not. I do not have a windows build system here. How did it behave before because Windows did not load the required textures?

In the shaders "static" was everywhere, this was not supported by OpenGL, is this "static" necessary under DirectX?

2019-02-09 18:37 UTC, AlwinEsch commented
On the Windows C++ is mostly nothing changed, only taken from ShaderToy the code of the glsl files thats why the changes looks there bigger.

Some code differences were in the glsl, but it was assumed that the code was updated on the website.

2019-02-09 19:11 UTC, afedchin requested changes
> How did it behave before because Windows did not load the required textures?

it doesn't use textures

> In the shaders "static" was everywhere, this was not supported by OpenGL, is this "static" necessary under DirectX?

iirc static is required for `const`.

I had a quick look into shaders changes, there are a lot of breaking changes:
1. HLSL can't multiply matrixes with operator `*` there is operator `muv` for this. removing `mul` makes shaders uncompilable.
2. `vec3(1.0)` (and similar) doesn't work on windows. only `vec3(1.0, 1.0, 1.0)` will (I've replaced each similar occerences manually)
3. HLSL on FL9.x has limitation on amount of shader operations and loops with 100 iterations may not work, because compiler unfolds loops.

2019-02-09 19:52 UTC, AlwinEsch commented on screensaver.shadertoy/resources/firefast.frag.glsl.orig
> -// Taken from https://www.shadertoy.com/view/4dlGR2
With *.orig says to me that something in the past was create by a "patch ..." call. Also was firefast not used.

2019-02-09 19:54 UTC, afedchin commented on screensaver.shadertoy/resources/firefast.frag.glsl.orig
> -// Taken from https://www.shadertoy.com/view/4dlGR2
you are right, no need keep them. orig means original shader code (from the site)

2019-02-21 11:05 UTC, Rechi commented on .travis.yml
> +# Some of the OS X images don't have cmake, contrary to what people
That's not true anymore.

2019-02-21 11:05 UTC, Rechi commented on .travis.yml
> +  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew update        ; fi
```suggestion
```

2019-02-21 11:05 UTC, Rechi commented on .travis.yml
> +  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew install cmake ; fi
```suggestion
```

2019-02-21 11:05 UTC, Rechi commented on .travis.yml
> +  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew upgrade cmake || true; fi
```suggestion
```

2019-02-21 11:05 UTC, Rechi commented on CMakeLists.txt
> +  if(NOT OPENGL_FOUND AND NOT OPENGLES_FOUND)
Make this the else branch in the above if.

2019-03-21 19:44 UTC, AlwinEsch commented
A small question.
After the "Angle" is in Kodi, do we switch this to primary as GL or leaving with the to DX translated shader code? If yes then I cleanup this after them is in Kodi.

2019-08-27 09:53 UTC, Rechi commented
@AlwinEsch this needs a rebase

2019-08-27 15:06 UTC, AlwinEsch commented
Is also in my workflow :grin:

2019-08-31 13:56 UTC, closed without merging